name = "gruvbox"

[colors]
identity_accent = "#fe8019"
identity_text   = "#d5c4a1"
text_primary    = "#ebdbb2"
text_secondary  = "#d5c4a1"
success         = "#b8bb26"
warning         = "#fabd2f"
danger          = "#fb4934"
info            = "#8ec07c"
muted           = "#928374"
track_dim       = "#504945"
